AllCops:
  TargetRubyVersion: 3.3.9
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  SafeAutoCorrect: true
  EnforcedStyle: always_true

Metrics/MethodLength:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Naming/FileName:
  Exclude:
    - "lib/replicate-client.rb"
